// src/constants/currencies.ts
export type Currency = {
  code: string;       // ISO 4217
  name: string;       // English common name
  symbol?: string;    // common symbol
  decimals?: number;  // minor units (ISO 4217)
};

/** Majors primero; luego el resto (selección amplia y útil). */
export const CURRENCIES: Currency[] = [
  { code: "USD", name: "US Dollar", symbol: "$", decimals: 2 },
  { code: "EUR", name: "Euro", symbol: "€", decimals: 2 },
  { code: "GBP", name: "Pound Sterling", symbol: "£", decimals: 2 },
  { code: "JPY", name: "Japanese Yen", symbol: "¥", decimals: 0 },
  { code: "CNY", name: "Chinese Yuan", symbol: "¥", decimals: 2 },
  { code: "AUD", name: "Australian Dollar", symbol: "$", decimals: 2 },
  { code: "CAD", name: "Canadian Dollar", symbol: "$", decimals: 2 },
  { code: "CHF", name: "Swiss Franc", symbol: "Fr", decimals: 2 },
  { code: "NZD", name: "New Zealand Dollar", symbol: "$", decimals: 2 },
  { code: "SEK", name: "Swedish Krona", symbol: "kr", decimals: 2 },
  { code: "NOK", name: "Norwegian Krone", symbol: "kr", decimals: 2 },
  { code: "DKK", name: "Danish Krone", symbol: "kr", decimals: 2 },
  { code: "SGD", name: "Singapore Dollar", symbol: "$", decimals: 2 },
  { code: "HKD", name: "Hong Kong Dollar", symbol: "$", decimals: 2 },
  { code: "KRW", name: "South Korean Won", symbol: "₩", decimals: 0 },
  { code: "INR", name: "Indian Rupee", symbol: "₹", decimals: 2 },
  { code: "BRL", name: "Brazilian Real", symbol: "R$", decimals: 2 },
  { code: "MXN", name: "Mexican Peso", symbol: "$", decimals: 2 },
  { code: "ZAR", name: "South African Rand", symbol: "R", decimals: 2 },
  { code: "RUB", name: "Russian Ruble", symbol: "₽", decimals: 2 },
  { code: "AED", name: "UAE Dirham", symbol: "د.إ", decimals: 2 },
  { code: "AFN", name: "Afghan Afghani", symbol: "؋", decimals: 2 },
  { code: "ALL", name: "Albanian Lek", symbol: "L", decimals: 2 },
  { code: "AMD", name: "Armenian Dram", symbol: "֏", decimals: 2 },
  { code: "AOA", name: "Angolan Kwanza", symbol: "Kz", decimals: 2 },
  { code: "ARS", name: "Argentine Peso", symbol: "$", decimals: 2 },
  { code: "AWG", name: "Aruban Florin", symbol: "ƒ", decimals: 2 },
  { code: "AZN", name: "Azerbaijani Manat", symbol: "₼", decimals: 2 },
  { code: "BAM", name: "Bosnia & Herzegovina Convertible Mark", symbol: "KM", decimals: 2 },
  { code: "BBD", name: "Barbados Dollar", symbol: "$", decimals: 2 },
  { code: "BDT", name: "Bangladeshi Taka", symbol: "৳", decimals: 2 },
  { code: "BGN", name: "Bulgarian Lev", symbol: "лв", decimals: 2 },
  { code: "BHD", name: "Bahraini Dinar", symbol: ".د.ب", decimals: 3 },
  { code: "BIF", name: "Burundian Franc", symbol: "Fr", decimals: 0 },
  { code: "BND", name: "Brunei Dollar", symbol: "$", decimals: 2 },
  { code: "BOB", name: "Boliviano", symbol: "Bs.", decimals: 2 },
  { code: "BSD", name: "Bahamian Dollar", symbol: "$", decimals: 2 },
  { code: "BTN", name: "Bhutanese Ngultrum", symbol: "Nu.", decimals: 2 },
  { code: "BWP", name: "Botswana Pula", symbol: "P", decimals: 2 },
  { code: "BYN", name: "Belarusian Ruble", symbol: "Br", decimals: 2 },
  { code: "BZD", name: "Belize Dollar", symbol: "$", decimals: 2 },
  { code: "CDF", name: "Congolese Franc", symbol: "Fr", decimals: 2 },
  { code: "CLP", name: "Chilean Peso", symbol: "$", decimals: 0 },
  { code: "COP", name: "Colombian Peso", symbol: "$", decimals: 2 },
  { code: "CRC", name: "Costa Rican Colón", symbol: "₡", decimals: 2 },
  { code: "CUP", name: "Cuban Peso", symbol: "$", decimals: 2 },
  { code: "CVE", name: "Cape Verdean Escudo", symbol: "$", decimals: 2 },
  { code: "CZK", name: "Czech Koruna", symbol: "Kč", decimals: 2 },
  { code: "DJF", name: "Djiboutian Franc", symbol: "Fr", decimals: 0 },
  { code: "DOP", name: "Dominican Peso", symbol: "RD$", decimals: 2 },
  { code: "DZD", name: "Algerian Dinar", symbol: "د.ج", decimals: 2 },
  { code: "EGP", name: "Egyptian Pound", symbol: "£", decimals: 2 },
  { code: "ERN", name: "Eritrean Nakfa", symbol: "Nfk", decimals: 2 },
  { code: "ETB", name: "Ethiopian Birr", symbol: "Br", decimals: 2 },
  { code: "FJD", name: "Fiji Dollar", symbol: "$", decimals: 2 },
  { code: "GEL", name: "Georgian Lari", symbol: "₾", decimals: 2 },
  { code: "GHS", name: "Ghanaian Cedi", symbol: "₵", decimals: 2 },
  { code: "GMD", name: "Gambian Dalasi", symbol: "D", decimals: 2 },
  { code: "GNF", name: "Guinean Franc", symbol: "Fr", decimals: 0 },
  { code: "GTQ", name: "Guatemalan Quetzal", symbol: "Q", decimals: 2 },
  { code: "GYD", name: "Guyanese Dollar", symbol: "$", decimals: 2 },
  { code: "HNL", name: "Honduran Lempira", symbol: "L", decimals: 2 },
  { code: "HTG", name: "Haitian Gourde", symbol: "G", decimals: 2 },
  { code: "HUF", name: "Hungarian Forint", symbol: "Ft", decimals: 2 },
  { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp", decimals: 2 },
  { code: "ILS", name: "Israeli New Shekel", symbol: "₪", decimals: 2 },
  { code: "IQD", name: "Iraqi Dinar", symbol: "ع.د", decimals: 3 },
  { code: "IRR", name: "Iranian Rial", symbol: "﷼", decimals: 2 },
  { code: "ISK", name: "Icelandic Króna", symbol: "kr", decimals: 0 },
  { code: "JMD", name: "Jamaican Dollar", symbol: "J$", decimals: 2 },
  { code: "JOD", name: "Jordanian Dinar", symbol: "د.أ", decimals: 3 },
  { code: "KES", name: "Kenyan Shilling", symbol: "KSh", decimals: 2 },
  { code: "KGS", name: "Kyrgyzstani Som", symbol: "сом", decimals: 2 },
  { code: "KHR", name: "Cambodian Riel", symbol: "៛", decimals: 2 },
  { code: "KMF", name: "Comorian Franc", symbol: "Fr", decimals: 0 },
  { code: "KWD", name: "Kuwaiti Dinar", symbol: "د.ك", decimals: 3 },
  { code: "KZT", name: "Kazakhstani Tenge", symbol: "₸", decimals: 2 },
  { code: "LAK", name: "Lao Kip", symbol: "₭", decimals: 2 },
  { code: "LBP", name: "Lebanese Pound", symbol: "ل.ل", decimals: 2 },
  { code: "LKR", name: "Sri Lankan Rupee", symbol: "Rs", decimals: 2 },
  { code: "LRD", name: "Liberian Dollar", symbol: "$", decimals: 2 },
  { code: "LSL", name: "Lesotho Loti", symbol: "L", decimals: 2 },
  { code: "LYD", name: "Libyan Dinar", symbol: "ل.د", decimals: 3 },
  { code: "MAD", name: "Moroccan Dirham", symbol: "د.م.", decimals: 2 },
  { code: "MDL", name: "Moldovan Leu", symbol: "L", decimals: 2 },
  { code: "MGA", name: "Malagasy Ariary", symbol: "Ar", decimals: 2 },
  { code: "MKD", name: "Macedonian Denar", symbol: "ден", decimals: 2 },
  { code: "MMK", name: "Myanmar Kyat", symbol: "K", decimals: 2 },
  { code: "MNT", name: "Mongolian Tögrög", symbol: "₮", decimals: 2 },
  { code: "MOP", name: "Macanese Pataca", symbol: "MOP$", decimals: 2 },
  { code: "MRU", name: "Mauritanian Ouguiya", symbol: "UM", decimals: 2 },
  { code: "MUR", name: "Mauritian Rupee", symbol: "₨", decimals: 2 },
  { code: "MVR", name: "Maldivian Rufiyaa", symbol: "Rf", decimals: 2 },
  { code: "MWK", name: "Malawian Kwacha", symbol: "MK", decimals: 2 },
  { code: "MYR", name: "Malaysian Ringgit", symbol: "RM", decimals: 2 },
  { code: "MZN", name: "Mozambican Metical", symbol: "MT", decimals: 2 },
  { code: "NAD", name: "Namibian Dollar", symbol: "$", decimals: 2 },
  { code: "NGN", name: "Nigerian Naira", symbol: "₦", decimals: 2 },
  { code: "NPR", name: "Nepalese Rupee", symbol: "₨", decimals: 2 },
  { code: "OMR", name: "Omani Rial", symbol: "ر.ع.", decimals: 3 },
  { code: "PAB", name: "Panamanian Balboa", symbol: "B/.", decimals: 2 },
  { code: "PEN", name: "Peruvian Sol", symbol: "S/.", decimals: 2 },
  { code: "PGK", name: "Papua New Guinean Kina", symbol: "K", decimals: 2 },
  { code: "PHP", name: "Philippine Peso", symbol: "₱", decimals: 2 },
  { code: "PKR", name: "Pakistani Rupee", symbol: "₨", decimals: 2 },
  { code: "PLN", name: "Polish Złoty", symbol: "zł", decimals: 2 },
  { code: "PYG", name: "Paraguayan Guaraní", symbol: "₲", decimals: 0 },
  { code: "QAR", name: "Qatari Riyal", symbol: "ر.ق", decimals: 2 },
  { code: "RON", name: "Romanian Leu", symbol: "lei", decimals: 2 },
  { code: "RSD", name: "Serbian Dinar", symbol: "дин.", decimals: 2 },
  { code: "RWF", name: "Rwandan Franc", symbol: "Fr", decimals: 0 },
  { code: "SAR", name: "Saudi Riyal", symbol: "ر.س", decimals: 2 },
  { code: "SBD", name: "Solomon Islands Dollar", symbol: "$", decimals: 2 },
  { code: "SCR", name: "Seychellois Rupee", symbol: "₨", decimals: 2 },
  { code: "SDG", name: "Sudanese Pound", symbol: "ج.س.", decimals: 2 },
  { code: "SOS", name: "Somali Shilling", symbol: "Sh", decimals: 2 },
  { code: "SRD", name: "Surinamese Dollar", symbol: "$", decimals: 2 },
  { code: "SSP", name: "South Sudanese Pound", symbol: "£", decimals: 2 },
  { code: "SYP", name: "Syrian Pound", symbol: "£", decimals: 2 },
  { code: "SZL", name: "Eswatini Lilangeni", symbol: "E", decimals: 2 },
  { code: "TND", name: "Tunisian Dinar", symbol: "د.ت", decimals: 3 },
  { code: "TOP", name: "Tongan Paʻanga", symbol: "T$", decimals: 2 },
  { code: "TRY", name: "Turkish Lira", symbol: "₺", decimals: 2 },
  { code: "TTD", name: "Trinidad and Tobago Dollar", symbol: "TT$", decimals: 2 },
  { code: "TWD", name: "New Taiwan Dollar", symbol: "NT$", decimals: 2 },
  { code: "TZS", name: "Tanzanian Shilling", symbol: "TSh", decimals: 2 },
  { code: "UAH", name: "Ukrainian Hryvnia", symbol: "₴", decimals: 2 },
  { code: "UGX", name: "Ugandan Shilling", symbol: "USh", decimals: 0 },
  { code: "UYU", name: "Uruguayan Peso", symbol: "$U", decimals: 2 },
  { code: "UZS", name: "Uzbekistani So'm", symbol: "so'm", decimals: 2 },
  { code: "VES", name: "Venezuelan Bolívar", symbol: "Bs.", decimals: 2 },
  { code: "VND", name: "Vietnamese Đồng", symbol: "₫", decimals: 0 },
  { code: "VUV", name: "Vanuatu Vatu", symbol: "Vt", decimals: 0 },
  { code: "WST", name: "Samoan Tālā", symbol: "T", decimals: 2 },
  { code: "XAF", name: "CFA Franc BEAC", symbol: "Fr", decimals: 0 },
  { code: "XOF", name: "CFA Franc BCEAO", symbol: "Fr", decimals: 0 },
  { code: "XPF", name: "CFP Franc", symbol: "Fr", decimals: 0 },
  { code: "YER", name: "Yemeni Rial", symbol: "﷼", decimals: 2 },
  { code: "ZMW", name: "Zambian Kwacha", symbol: "ZK", decimals: 2 },
  { code: "ZWL", name: "Zimbabwean Dollar", symbol: "Z$", decimals: 2 },
];

export const CURRENCY_CODES = CURRENCIES.map(c => c.code);